---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-customer
  template:
    metadata:
      labels:
        app: frontend-customer
    spec:
      containers:
        - name: frontend-customer
          image: bakery-frontend-customer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-customer
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 32173
  selector:
    app: frontend-customer
