---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-orders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cakes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-orders
spec:
  ports:
    - port: 5432
  selector:
    app: db-orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-orders
spec:
  selector:
    matchLabels:
      app: db-orders
  template:
    metadata:
      labels:
        app: db-orders
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: db_orders
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              value: testpass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-data-orders
---
apiVersion: v1
kind: Service
metadata:
  name: db-cakes
spec:
  ports:
    - port: 5432
  selector:
    app: db-cakes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-cakes
spec:
  selector:
    matchLabels:
      app: db-cakes
  template:
    metadata:
      labels:
        app: db-cakes
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: db_cakes
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              value: testpass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-data-cakes
