name: E2E Playwright Tests

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      docker:
        image: docker:24.0.2-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start backend and frontend (docker-compose)
        run: |
          docker-compose up -d frontend-customer backend-customer backend-admin db_orders db_cakes
        working-directory: ${{ github.workspace }}

      - name: Wait for frontend-customer to be ready
        run: |
          for i in {1..40}; do
            if curl -sSf http://localhost:5173 > /dev/null; then
              echo "Frontend is up!"
              exit 0
            fi
            sleep 3
          done
          echo "Frontend did not become ready in time." && exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install E2E dependencies
        run: |
          cd 'E2E tests'
          npm ci

      - name: Install Playwright browsers
        run: |
          cd 'E2E tests'
          npx playwright install --with-deps

      - name: Run Playwright E2E tests
        run: |
          cd 'E2E tests'
          npm test

      - name: Upload Playwright test results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: E2E tests/playwright-report
          if-no-files-found: ignore
